jdk:
    vendor:
        name: Oracle-JDK
        version: ${java.version}
gradle:
    version: 8.7
    DSL: Kotlin
spring:
  application:
    name: AI-Expert-RAG
    version: 0.0.1-SNAPSHOT
    description: DEMO AI Expert RAG project for using the Mistral AI api and Milvus vectorDB
  output:
    ansi:
      enabled: always
  config:
    import: classpath:env/Mistral.env[.properties]
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: mistral-small-latest
          temperature: 0.8
ysy:
  aiapp:
      vectorStorePath: /tmp/vectorStore.json
      documentsToLoad:
        - classpath:/movies50Trimmed.csv
